# Generated by Django 4.0.4 on 2022-04-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
            ],
        ),
    ]
